apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: oidc-selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-cert
  namespace: istio-system
spec:
  commonName: oidc.carbide.rfed.dev
  secretName: oidc-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - oidc.carbide.rfed.dev
  duration: 87660h0m0s
  issuerRef:
    name: oidc-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io