apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-rancher-carbide-cert
  namespace: istio-system
spec:
  commonName: '*.staging.ranchercarbide.dev'
  secretName: staging-rancher-carbide-cert
  dnsNames:
  - staging.ranchercarbide.dev
  - '*.staging.ranchercarbide.dev'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod